import argparse
import re
from pathlib import Path


PORT_RE = re.compile(r"^\s*(INPUT|OUTPUT)\s*\(\s*([^()]+?)\s*\)\s*(?:#.*)?$", re.IGNORECASE)
GATE_RE = re.compile(
    r"^\s*([A-Za-z0-9_.\[\]]+)\s*=\s*([A-Za-z][A-Za-z0-9_]*)"
    r"\s*\(([^()]*)\)\s*(?:#.*)?$"
)


def _append_unique(values: list[str], seen: set[str], value: str) -> None:
    if value not in seen:
        seen.add(value)
        values.append(value)


def convert_full_scan(source: Path, destination: Path) -> dict[str, int]:
    source = source.resolve()
    destination = destination.resolve()
    if source == destination:
        raise ValueError("Source and destination must be different files.")

    raw_lines = source.read_text(encoding="utf-8").splitlines()
    header_comments: list[str] = []
    primary_inputs: list[str] = []
    primary_outputs: list[str] = []
    seen_inputs: set[str] = set()
    seen_outputs: set[str] = set()
    input_comments: dict[str, str] = {}
    output_comments: dict[str, str] = {}
    dffs: list[tuple[str, str, int]] = []
    dff_outputs: set[str] = set()
    combinational_outputs: set[str] = set()
    body: list[str] = []
    saw_record = False

    for line_no, raw_line in enumerate(raw_lines, start=1):
        content = raw_line.split("#", 1)[0].strip()
        if not content:
            if not saw_record:
                header_comments.append(raw_line)
            elif raw_line.strip().startswith("#"):
                body.append(raw_line)
            continue

        saw_record = True
        port_match = PORT_RE.fullmatch(raw_line)
        if port_match:
            kind, name = port_match.groups()
            comment = ""
            if "#" in raw_line:
                comment = " #" + raw_line.split("#", 1)[1].rstrip()
            if kind.upper() == "INPUT":
                _append_unique(primary_inputs, seen_inputs, name)
                input_comments.setdefault(name, comment)
            else:
                _append_unique(primary_outputs, seen_outputs, name)
                output_comments.setdefault(name, comment)
            continue

        gate_match = GATE_RE.fullmatch(raw_line)
        if not gate_match:
            if "DFF" in content.upper():
                raise ValueError(f"Malformed DFF record on line {line_no}: {raw_line}")
            raise ValueError(f"Malformed BENCH record on line {line_no}: {raw_line}")

        output_name, gate_type, fanin_text = gate_match.groups()
        if gate_type.upper() == "DFF":
            fanins = [part.strip() for part in fanin_text.split(",")]
            if len(fanins) != 1 or not fanins[0]:
                raise ValueError(
                    f"DFF on line {line_no} must have exactly one input: {raw_line}"
                )
            if output_name in dff_outputs:
                raise ValueError(f"Duplicate DFF output '{output_name}' on line {line_no}.")
            dff_outputs.add(output_name)
            dffs.append((output_name, fanins[0], line_no))
            continue

        if output_name in combinational_outputs:
            raise ValueError(
                f"Duplicate combinational driver for '{output_name}' on line {line_no}."
            )
        combinational_outputs.add(output_name)
        body.append(raw_line)

    conflicts = sorted(dff_outputs & combinational_outputs)
    if conflicts:
        examples = ", ".join(conflicts[:10])
        raise ValueError(f"DFF outputs also driven by combinational gates: {examples}")
    if not dffs:
        raise ValueError(f"No DFF records found in {source}.")

    for q_name, d_name, _ in dffs:
        _append_unique(primary_inputs, seen_inputs, q_name)
        _append_unique(primary_outputs, seen_outputs, d_name)

    input_driver_conflicts = sorted(seen_inputs & combinational_outputs)
    if input_driver_conflicts:
        examples = ", ".join(input_driver_conflicts[:10])
        raise ValueError(f"Primary inputs also driven by combinational gates: {examples}")

    output_lines = [
        "# Full-scan combinational model generated by convert_full_scan_bench.py",
        f"# Source: {source.name}",
        f"# Cut DFFs: {len(dffs)}",
        "",
        *header_comments,
        *(f"INPUT({name}){input_comments.get(name, '')}" for name in primary_inputs),
        "",
        *(f"OUTPUT({name}){output_comments.get(name, '')}" for name in primary_outputs),
        "",
        *body,
        "",
    ]
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8", newline="\n") as output:
        output.write("\n".join(output_lines))
    return {
        "dffs_cut": len(dffs),
        "primary_inputs": len(primary_inputs),
        "primary_outputs": len(primary_outputs),
        "combinational_gates": len(combinational_outputs),
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Cut BENCH DFFs into pseudo primary inputs and outputs."
    )
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()

    stats = convert_full_scan(args.source, args.destination)
    print(
        "Converted full-scan BENCH: "
        f"dffs={stats['dffs_cut']} inputs={stats['primary_inputs']} "
        f"outputs={stats['primary_outputs']} gates={stats['combinational_gates']}"
    )
    print(f"Output: {args.destination.resolve()}")


if __name__ == "__main__":
    main()
